version: "3.1"

services:
  mawaqit_php:
    container_name: mawaqit_php
    build: docker/php-fpm/raspberry
    restart: always
    environment:
      APP_ENV: raspberry
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      # clock
      - /etc/localtime:/etc/localtime:ro

  mawaqit_nginx:
    container_name: mawaqit_nginx
    image: arm32v6/nginx:alpine
    restart: always
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/raspberry.conf:/etc/nginx/conf.d/default.conf
      # clock
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80

  mawaqit_mysql:
    container_name: mawaqit_mysql
    image: yobasystems/alpine-mariadb:arm32v7
    restart: always
    volumes:
      - /var/www/mawaqit/docker/data/mysql:/var/lib/mysql
     # clock
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: mawaqit
      MYSQL_DATABASE: mawaqit

  mawaqit_composer:
    image: arm32v6/composer
    volumes:
      - ./:/app
    command: install -o -n
