imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            action_level: error
            level: debug
            max_files: 10
            channels: ['!event']
            
hautelook_alice:
    fixtures_path: 'Resources/fixtures/orm'

swiftmailer:
    disable_delivery: true

