imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    translator: { fallbacks: [en, fr] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
        
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~        
    bundles:
        - AppBundle        

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      supportEmail: "%supportEmail%"
      supportTel1: "%supportTel1%"
      supportTel2: "%supportTel2%"
      site: "%site%"
    form_themes:
        - 'form/themes.html.twig'
        - 'VichUploaderBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        server_version: '5.6'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    default_mailer: memory
    mailers:
        memory:
            transport: '%mailer_transport%'
            host: '%mailer_host%'
            port: '%mailer_port%'
            username: '%mailer_user%'
            password: '%mailer_password%'
            sender_address: '%supportEmail%'
            spool:
                type: memory
        file:
            transport: '%mailer_transport%'
            host: '%mailer_host%'
            port: '%mailer_port%'
            username: '%mailer_user%'
            password: '%mailer_password%'
            sender_address: '%supportEmail%'
            spool:
                type: file
                path: '%mailer_spool_dir%'

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: '%no_reply_address%'
        sender_name: '%name%'
    registration:
        form:
            type: AppBundle\Form\RegistrationType
            validation_groups: [Registration, appChangePassword]
        confirmation:
            enabled: true
    change_password:
        form:
            validation_groups: [appChangePassword]
    resetting: ~

vich_uploader:
    db_driver: orm
    mappings:
        image:
            uri_prefix: /upload/images
            upload_destination: '%kernel.root_dir%/../web/upload/images'
            namer:  vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        distinct: true
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'
        
mobile_detect: ~

jms_i18n_routing:
    default_locale: "%locale%"
    locales: "%languages%"
    strategy: prefix

stfalcon_tinymce:
  tinymce_jquery: true
  theme:
      simple:
          height: 400
          fontsize_formats: "100% 120% 140% 160% 180% 200% 250% 300% 400%"
          plugins:
            - "advlist autolink autosave link image lists charmap preview hr"
            - "visualblocks visualchars code insertdatetime nonbreaking media"
            - "table contextmenu directionality emoticons template textcolor paste textcolor colorpicker textpattern"
          toolbar1: "undo redo | formatselect fontselect fontsizeselect forecolor backcolor | removeformat | bold italic underline strikethrough | charmap emoticons"
          toolbar2: " | alignleft aligncenter alignright alignjustify | bullist numlist | outdent indent | link unlink image media | insertdatetime | table | hr | subscript superscript | code preview"