security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: mosque_index
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                use_referer: true
            logout:     
                path:  fos_user_security_logout
                target: homepage
            remember_me:
                secret:   '%secret%'
                lifetime: 31536000 # 1 year
                path:     /
                secure: true

    access_control:
        # IS_AUTHENTICATED_ANONYMOUSLY
        - { path: /admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # ROLE_ADMIN
        - { path: /admin/user, role: ROLE_ADMIN }
        - { path: /admin/tools, role: ROLE_ADMIN }
        - { path: /admin/stats, role: ROLE_ADMIN }
        - { path: /admin/faq, role: ROLE_ADMIN }
        # ROLE_USER for all rest of /admin routes
        - { path: /admin, role: ROLE_USER }
