security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        api_user:
            entity:
              class: AppBundle\Entity\User
              property: apiAccessToken


    firewalls:
        local:
            host: ^mawaqit.local$
            security: false
        api:
            stateless: true
            pattern: ^/api
            simple_preauth:
                authenticator: app.security.uuid_token_authenticator
            provider: api_user
        main:
            pattern: ^/
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: mosque_index
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                use_referer: true
            logout:     
                path:  fos_user_security_logout
                target: homepage
            remember_me:
                secret:   '%secret%'
                lifetime: 31536000 # 1 year
                path:     /
                secure: true

    access_control:
        # IS_AUTHENTICATED_ANONYMOUSLY
        - { path: /backoffice/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /backoffice/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /backoffice/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: /backoffice/admin, role: ROLE_ADMIN }

        - { path: /backoffice, role: ROLE_USER }
        - { path: /api, role: ROLE_USER }
