AppBundle\Entity\Configuration:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ConfigurationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        jumuaTime:
            type: string
            nullable: true
        jumuaTime2:
            type: string
            nullable: true
        jumuaAsDuhr:
            type: boolean             
        jumua:
            type: boolean             
        jumuaDhikrReminderEnabled:
            type: boolean             
        jumuaBlackScreenEnabled:
            type: boolean             
        jumuaTimeout:
            type: integer             
        aidTime:
            type: string
            nullable: true
        imsakNbMinBeforeFajr:
            type: smallint
            nullable: true
        maximumIshaTimeForNoWaiting:
            type: string
            nullable: true
        waitingTimes:
            type: simple_array
        adjustedTimes:
            type: simple_array
            nullable: true
        fixedTimes:
            type: simple_array
            nullable: true
        fixedIqama:
            type: simple_array
            nullable: true
        duaAfterPrayerShowTimes:
            type: simple_array
        hijriAdjustment:
            type: smallint
        hijriDateEnabled:
            type: boolean
        duaAfterAzanEnabled:
            type: boolean
        duaAfterPrayerEnabled:
            type: boolean
        urlQrCodeEnabled:
            type: boolean
        azanBip:
            type: boolean
        azanVoiceEnabled:
            type: boolean
        iqamaBip:
            type: boolean
        iqamaEnabled:
            type: boolean
        iqamaFullScreenCountdown:
            type: boolean
        iqamaDisplayTime:
            type: smallint
        blackScreenWhenPraying:
            type: boolean
        randomHadithEnabled:
            type: boolean
        randomHadithIntervalDisabling:
            type: string
            nullable: true
        temperatureEnabled:
            type: boolean
        temperatureUnit:
            type: string
        sourceCalcul:
            type: string
        prayerMethod:
            type: string
            nullable: true
        asrMethod:
            type: string
        highLatsMethod:
            type: string
            nullable: true
        timezoneName:
            type: string
        dst:
            type: smallint
        dstSummerDate:
            type: date
            nullable: true
        dstWinterDate:
            type: date
            nullable: true
        hadithLang:
            type: string
            length: 50
        fajrDegree:
            type: smallint
            nullable: true
        ishaDegree:
            type: smallint
            nullable: true
        wakeForFajrTime:
            type: smallint
            nullable: true
        wakeAzanVoice:
            type: string
        calendar:
            type: json
            nullable: true
        iqamaCalendar:
            type: json
            nullable: true
        ishaFixation:
            type: smallint
            nullable: true
        footer:
            type: boolean
        timeToDisplayMessage:
            type: smallint
        timeDisplayFormat:
            type: string
        showNextAdhanCountdown:
            type: boolean
        backgroundType:
            type: string
        backgroundColor:
            type: string
        backgroundMotif:
            type: string
        theme:
            type: string
        updated:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update