AppBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: AppBundle\Repository\UserRepository
    lifecycleCallbacks:
      preUpdate: [attributeApiAccessToken]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        tou:
          type: boolean
        apiAccessToken:
          type : uuid
          unique: true
          nullable: true
        apiQuota:
          type : integer
          nullable: true
        apiCallNumber:
          type : integer
          nullable: true
        apiUseDescription:
          type : text
          nullable: true
        mosqueQuota:
          type : integer
          nullable: true
        created:
            type: datetime
            nullable: true
        updated:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        mosques:
            targetEntity: AppBundle\Entity\Mosque
            mappedBy: user