easy_admin:
  site_name: Mawaqit | Super admin
  design:
    brand_color: '#448531'
    menu:
      - { entity: Mosque, label: Mosquées, icon: building, default: true }
      - { entity: User, label: Utilisateurs, icon: user }
      - { entity: Faq, icon: question}
      - { entity: Parameters, label: Paramètres, icon: cog}
      - { label: Retour au backoffice, route: 'mosque_index' }
    form_theme:
      - "easyadmin/form.html.twig"
  formats:
    date:     d/m/Y
    time:     H:i
    datetime: d/m/Y H:i